# Environment YAML File: azureml/environment.yml
name: anomaly-env
channels:
  - conda-forge
dependencies:
  # Python Version
  - python=3.10 
  # Core ML libraries
  - pip:
    - azure-ai-ml
    - azure-identity
    - pandas
    - scikit-learn==1.3.0 # Specific versioning is good practice
    - matplotlib
    - seaborn
    - mlflow # Critical for logging/tracking
    - pip>=21.2.4
    - setuptools>=65.5.1